### ISSUE TITLE
Merging leapofazzam123/limine with limine-zig?

### ISSUE THREAD

**Issue by leap0x7b** [48cf/limine-zig#1]
I created the Limine library for Zig first before the official library did, and the official library is a mess right now. Maybe @czapek1337 and @mintsuki could merge my library with yours?

https://github.com/leapofazzam123/limine

**Comment by 48cf** [comment]
im gonna have to (respectfully) decline your offer, i dont particularly like your code and would like to keep limine-zig as simple and close to the specification as possible, but thanks :)

**Comment by Andy-Python-Programmer** [comment]
based response

**Comment by leap0x7b** [comment]
> im gonna have to (respectfully) decline your offer, i dont particularly like your code and would like to keep limine-zig as simple and close to the specification as possible, but thanks :)

![IMG_20220909_172655.png](https://user-images.githubusercontent.com/76893443/189329881-20759f6a-cd2b-4f60-a41b-a23a6abcd80b.png)
